version: "3.8"

services:

  generator:
    build:
      context: ./generator/
      dockerfile: Dockerfile
    container_name: generator
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    environment:
      - DB_URL=smartdb:27017
      - DB_NAME=SmartParty
    depends_on:
      - rabbitmq
    networks:
      - net
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: on-failure
    depends_on:
      - api
    networks:
      - net
    ports:
      - "8080:80"

  smartdb:
    image: mongo
    container_name: smartdb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: SmartParty
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: student
    networks:
      - net
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: student
      ME_CONFIG_MONGODB_URL: mongodb://root:student@smartdb:27017/ 
    networks:
      - net

networks:
  net:
